spring:
  profiles:
    active: dev
emp:
  name: fengb
---
spring:
  profiles: dev
server:
  port: 8762
eureka:
  instance:
    hostname: eureka8761.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8762.com:8762/eureka/
  server:
    enable-self-preservation: false
---
spring:
  profiles: prod
server:
  port: 8761
eureka:
  instance:
    hostname: eureka8761.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8762.com:8762/eureka/
  server:
    enable-self-preservation: false
